### ISSUE TITLE
Add support for Zabbix monitoring system

### ISSUE THREAD

**Issue by andli86** [c-toolbox/C-Troll#3]
I would like to have support for [Zabbix](http://www.zabbix.com/) i C-Troll.
To be able to monitor if the diffrent components (core, tray...) are running or not.
It's also possible to send data to Zabbix, such as if programs controlled by C-Troll is started (also which program, if you want to get detailed information).
This would be great for supoort staff, to see if the system is healthy and for managers to see usage of diffrent programs/shows. It's also possible in Zabbix to act on triggers, to send an e-mail or SMS if something is wrong.

OS specific monitoring, is best done with the Zabbix agents, which can gather information about CPU, Mem, Disk, Network usage to name a few items.

**Comment by alexanderbock** [comment]
This can be now more independently handled through the REST api;

A GET request to `URL:PORT/api/node`  will return a list of all available nodes and whether these are connected or not.
1. If the request succeeds, C-Troll is available
1. In the request, all nodes have a `isConnected` flag that is `true` if the Tray on that machine is visible from _C-Troll_
