### ISSUE TITLE
Tray and Editor should default to the same port

### ISSUE THREAD

**Issue by micahnyc** [c-toolbox/C-Troll#52]
right now they default to different ones....

**Comment by alexanderbock** [comment]
Can you provide more info?

The Tray's default configuration uses port 5000:
![image](https://user-images.githubusercontent.com/4921724/210172857-e49ec335-3c41-4acb-b4e4-f5c1202c08c4.png)

as does the Editor:
![image](https://user-images.githubusercontent.com/4921724/210172863-b9a1b8e7-3d4c-4775-91db-2a8cbcd157fd.png)

**Comment by alexanderbock** [comment]
https://github.com/c-toolbox/C-Troll/blob/master/src/tray/configuration.h#L46
